apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - name: http
    nodePort: 31090
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30445
    port: 443
    protocol: TCP
    targetPort: 8080 # Direcionando para HTTP pois o pod esta em modo --insecure
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
