apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: dev
spec:
  hard:
    requests.cpu: "8000m"
    requests.memory: "20Gi"
    limits.cpu: "16000m"
    limits.memory: "32Gi"
    pods: "100"
